name: CI_Parameter_Timer
on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'tb'
  workflow_dispatch:

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: docker build -t timer .
      - name: tag image
        run: docker tag timer ${{ secrets.DOCKER_USERNAME }}/timer:v1.0
      - name: push image to docker hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/timer:v1.0
      - name: Remove pre existing image 
        run: |
          docker rmi ${{ secrets.DOCKER_USERNAME }}/timer:v1.0
  Test_Timer:
    runs-on: ubuntu-latest
    steps:  
      - name: Testing Timer
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker pull ${{ secrets.DOCKER_USERNAME }}/timer:v1.0
      - name: Running Timer
        run: docker run ${{ secrets.DOCKER_USERNAME }}/timer:v1.0
        
          
          
                
          
          
